vindi/vindi-magento

src/app/code/community/Vindi/Subscription/Model/BankSlip.php
src/app/code/community/Vindi/Subscription/Model/CreditCard.php
src/app/code/community/Vindi/Subscription/Trait/PaymentMethod.php

O Magento estava atribuindo status "payment_review" nos pedidos sem confirmação de pagamento, esse PR altera o status de "payment_review" para "pending_payment".
Precisamos alterar isso porque o status anterior só é usado em casos de suspeita de fraude, e isso limita algumas opções do pedido dentro do Magento.

Altera o status do pedido de payment_review para pending_payment [MOD-23]

---

src/app/code/community/Vindi/Subscription/Model/CreditCard.php

Faz com que o payment_method_code seja enviado ao criar um perfil de
pagamento.

Correção na criação de perfil de pagamento [DEV-375]

---

CHANGELOG.md
src/app/code/community/Vindi/Subscription/Model/BankSlip.php
src/app/code/community/Vindi/Subscription/etc/config.xml

Enviando parcela do boleto sempre como 1 pois se o plano estiver configurado com mais parcelas do lado da Vindi, a plataforma irá retornar um 422.

[DEV-726] Fixando parcelamento do boleto em 1

---

src/app/code/community/Vindi/Subscription/Helper/WebhookHandler.php

O código removido estava fazendo com que o método exibisse um erro ao usá-lo.

Ajuste no link do webhook, método createOrder

---

CHANGELOG.md
src/app/code/community/Vindi/Subscription/Helper/Api.php
src/app/code/community/Vindi/Subscription/Model/CreditCard.php
src/app/code/community/Vindi/Subscription/etc/config.xml
src/app/code/community/Vindi/Subscription/etc/system.xml

Atualmente o módulo da Vindi para Magento não possui a transação de verificação, o que impossibilita os clientes Vindi de instalarem/utilizaram essa funcionalidade.
Essa extensão pode ser indicada como um diferencial para os clientes, aumentando a confiabilitade do negócio dele tanto quanto um ganho de receita para a Vindi.
Esse PR adiciona uma opção para habilitar a função de transação de verificação da Vindi no módulo Magento, que impede a compra nas verificações rejeitadas.

Adição da Transação de Verificação

---

src/app/code/community/Vindi/Subscription/etc/config.xml

- Os pedidos com status pending_payment não aparecem na sessão orders do painel administrativo do Magento
- Forçar a exibição desse tipo de pedido

exibe pedido pendente na area do cliente

---

src/app/code/community/Vindi/Subscription/Helper/Api.php
src/app/code/community/Vindi/Subscription/Trait/PaymentMethod.php

O modelo de negócio atual da Vindi, requer que caso o pagamento não seja aprovado na primeira tentativa (**compras avulsas ou primeiro ciclo de uma assinatura**), a fatura e o pedido sejam cancelados.
Porém, no Magento o cliente recebe a informação que o pedido foi registrado com sucesso, e posteriormente recebe a informação de falha no pagamento.
Adicionar o cancelamento automático de faturas na Vindi após a recusa de uma transação no Magento.
As compras via **Boleto** ou _pendente de revisões do **Antifraude**_ não são canceladas automaticamente.

Cancelamento automático de compras reprovadas

---

src/app/code/community/Vindi/Subscription/Model/CreditCard.php
src/app/code/community/Vindi/Subscription/Model/DebitCard.php
src/app/code/community/Vindi/Subscription/Trait/PaymentMethod.php

Nas renovações de assinaturas, ao executar o método **createOrder** está sendo retornado o erro de 'Data de expiração do cartão incorreta', pois o método não existe nessa classe. (apenas para cartão de débito)
Mover o método **validateExpDate** para a classe _Perfil de Pagamentos_, tornando-o disponível tanto para Cartão de crédito como débito.

Adiciona método para validação da data de Expiração do Cartão de Crédito

---

src/app/code/community/Vindi/Subscription/Helper/Api.php
src/app/code/community/Vindi/Subscription/Model/Observer.php

Atualmente não é possível realizar a compra de mais de 1 item do tipo assinatura no Magento mesmo que sejam do mesmo Plano.
Criação de um método para validação do carrinho, que bloqueie apenas a compra de assinaturas com recorrências diferentes.

Adiciona compatibilidade com quantidade de assinaturas

---

README.md

- A Instalação do modman pode ser um pouco complexa para alguns usuários, obrigado-os a realizar a instalação manual, que pode causar uma inconsistência no módulo;
- O local dos Webhooks na Plataforma da Vindi foi alterado.
- Alteração do método de instalação de [modman](https://github.com/colinmollenhour/modman) para [modgit](https://github.com/jreinke/modgit), pois é mais fácil de ser instalado, e realizar a gestão do módulo Vindi.
- Ajuste no local da configuração dos Webhooks.

Melhora documentação

---

CHANGELOG.md
src/app/code/community/Vindi/Subscription/Block/Form/Cc.php
src/app/code/community/Vindi/Subscription/Trait/PaymentMethod.php
src/app/code/community/Vindi/Subscription/etc/config.xml

Após a implementação das quantidades de assinaturas, e compras variáveis (simples/recorrentes); O plano não está sendo obtido caso o primeiro produto do carrinho seja um produto simples, pois a verificação é realizada apenas no primeiro item do carrinho.
A primeira quantidade de parcelas válida é informada, e caso não seja possível parcelar, é retornado **null** (à vista).

Ajusta installments compra variada

---

src/app/code/community/Vindi/Subscription/Trait/PaymentMethod.php

Com a remoção do GET adicional na criação das faturas #61, o retorno da assinatura não está sendo tratado corretamente, consequentemente deixando o pedido com status **pagamento pendente**.
Retornar a fatura completa contida na assinatura, possibilitando a validação do status e demais informações presentes.

Ajusta método de criação de assinaturas

---

CHANGELOG.md
src/app/code/community/Vindi/Subscription/Helper/Api.php
src/app/code/community/Vindi/Subscription/etc/config.xml

A Taxa do Magento não estava sendo enviada para a Vindi, causando a divergência de valores cobrados entre Vindi x Magento.
Adicionar método de criação de um produto com o nome de Taxa, que recebe o valor de todas as taxas no carrinho.

Adiciona envio de taxa

---

CHANGELOG.md
src/app/code/community/Vindi/Subscription/Helper/Api.php
src/app/code/community/Vindi/Subscription/etc/config.xml

A validação das taxas está retornando um **fatal error** que não foi reproduzido nos testes.
Alterar o modo de validação de **isset** para **array_key_exists**.

Altera validação no método de criação de taxas

---

app/code/community/Vindi/Subscription/Model/Observer.php

A descrição não estava funcionando corretamente, pois a princípio o valor de _lastProduct_ não está setado.
Alterar a validação para isset(lastProduct) para garantir que não será gerado nenhum erro.

Ajusta validação de produtos no carrinho

---

app/code/community/Vindi/Subscription/Trait/PaymentMethod.php

[#1742](https://github.com/vindi/recurrent/issues/1742)
Não está sendo possível realizar compras quando o antifraude [Konduto](https://www.konduto.com/) declara uma transação como "**suspeita de fraude**".
Atualmente, o cliente recebe a informação que houve um erro ao processar o pagamento e a compra, cancelando a compra, pois o **status da cobrança** não é tratado no Magento;
Quando a transação é categorizada como suspeita, é necessário aguardar uma análise da [Konduto](https://www.konduto.com/), que posteriormente atualiza a transação para *aprovada* **ou** *rejeitada*.
Adicionar a validação para o status '**fraund_review**', dentro da **Charge** da **Fatura** atual.

Adiciona suporte à suspeita de fraude com aprovação via Konduto

---

app/code/community/Vindi/Subscription/Helper/WebhookHandler.php
app/code/community/Vindi/Subscription/Model/Observer.php
app/code/community/Vindi/Subscription/Trait/PaymentMethod.php

O módulo está sendo recusado pelo Marketplace por erros 'legado'.
Remover as chamadas do método **exit** utilizado para jogar uma mensagem de erro por padrão no Magento.

Aplica ajuste do Marketplace

---

CHANGELOG.md
app/code/community/Vindi/Subscription/Helper/Api.php
app/code/community/Vindi/Subscription/etc/config.xml

Foi feita uma alteração no recurrent para viabilizar o uso de cartão de débito via api. Nessa alteração, retornamos o atributo `redirect_url` que aponta para a rota responsável por criar a transação de autorização, mantendo os headers da requisição do usuário final de ponta a ponta.
Atualizar a função `getDebitCardRedirectUrl` para pegar o `redirect_url` em vez de `authorization_url` no `gateway_response_fields`

Atualiza debit card redirect_url

---

app/code/community/Vindi/Subscription/Helper/Bill.php
app/code/community/Vindi/Subscription/Helper/Logger.php
app/code/community/Vindi/Subscription/Helper/Order.php
app/code/community/Vindi/Subscription/Helper/Validator.php
app/code/community/Vindi/Subscription/Helper/WebhookHandler.php
app/code/community/Vindi/Subscription/controllers/WebhookController.php

- O código do Magento está com alguns problemas de design, dificuldando qualquer alteração, seja para correção de bugs ou para adição de novas funcionalidades.
- Aparentemente os Webhooks não estão atuando da forma que deveriam.
O pedido deve ser criado no Magento com os valores atualizados de acordo com a assinatura na Vindi
O pedido deve ser atualizado para o status '_processing_', e os valores de pagamento devem ser síncronos com os visualizados na Vindi.
O pedido deve receber a mensagem de falha na tentativa de cobrança;
Caso seja a última tentativa, o pedido deve receber o status '_cancelled_'

Refatoração das classes de Webhook

---

CHANGELOG.md
app/code/community/Vindi/Subscription/Helper/Bill.php
app/code/community/Vindi/Subscription/Helper/Order.php
app/code/community/Vindi/Subscription/etc/config.xml

Issue: [#1825](https://github.com/vindi/recurrent/issues/1825) e [#1823](https://github.com/vindi/recurrent/issues/1823)
Ao realizar uma alteração na assinatura/ fatura via plataforma Vindi, os dados alterados não são refletidos no módulo Magento.
- Validar o valor do produto Vindi obtido no webhook de Fatura criada (bill_created) e atualizar o Magento com os mesmos.
- Validar os produtos que expiraram ou foram removidos da assinatura na Vindi, para que não sejam exibidos no pedido do Magento.

Corrige sincronização de fatura e pedido

---

CHANGELOG.md
app/code/community/Vindi/Subscription/Block/Form/BankSlip.php
app/code/community/Vindi/Subscription/etc/config.xml
app/design/adminhtml/base/default/template/vindi_subscription/payment/form/bankslip.phtml
app/design/frontend/base/default/template/vindi_subscription/payment/form/bankslip.phtml

Issue: [#1883](https://github.com/vindi/recurrent/issues/1883)
Atualmente a mensagem para o consumidor ao escolher Boleto como método de pagamento é um pouco confusa.
Mesmo selecionando uma assinatura com periodicidade semanal (por exemplo), é exibida a mensagem:
```` O boleto será enviado mensalmente para o seu email. ````
E na verdade a periodicidade não é mensal.
Juntamente com a Equipe de UX definir e implementar uma mensagem mais agradável ao consumidor;
- Foi selecionada uma mensagem padrão que independe da periodicidade da assinatura
```` O boleto bancário será enviado para o seu e-mail. ````

Ajusta mensagem do método de pagamento Boleto

---

CHANGELOG.md
app/code/community/Vindi/Subscription/Helper/Order.php
app/code/community/Vindi/Subscription/Helper/Validator.php
app/code/community/Vindi/Subscription/etc/config.xml
app/code/community/Vindi/Subscription/etc/system.xml

Atualmente, se um _webhook_ de renovação for perdido, os _webhooks_ de ciclos posteriores são rejeitados.
A renovação requer que o último ciclo renovado seja exatamente o ciclo **anterior ao atual**.
Ex: 
- Na chegada da renovação [Ciclo: **10**]
- É necessário que o Magento possua o pedido [Ciclo: **9**]
- Remover a validação do último ciclo para o webhook **bill_created**;
- Buscar algum pedido da assinatura em questão;
A renovação será processada se:
- Houver um pedido **com o ciclo anterior**
- Houver algum pedido **referente a assinatura** em questão

Ajusta comportamento para Webhook de Fatura Criada (bill_created)

---

app/code/community/Vindi/Subscription/Helper/Order.php

O Payment da Order está sendo utilizado duas vezes, e está retornando null.
Utilizar o método getPayment somente em um local.

Corrige atribuição de Order/Payment

---

CHANGELOG.md
app/code/community/Vindi/Subscription/Helper/Validator.php
app/code/community/Vindi/Subscription/etc/config.xml

Caso haja uma nova captura com status rejeitado em uma cobrança já paga, o pedido está sofrendo alterações no Magento.
Bloquear alterações no pedido se a Cobrança já possuir um estado final ('paid')

Ajusta evento 'charge_rejected' para cartão de débito

---

app/code/community/Vindi/Subscription/Helper/Bill.php
app/code/community/Vindi/Subscription/Helper/Order.php
app/code/community/Vindi/Subscription/Helper/Validator.php
app/code/community/Vindi/Subscription/Helper/WebhookHandler.php
app/code/community/Vindi/Subscription/controllers/WebhookController.php

Issue: [#2144](https://github.com/vindi/recurrent/issues/2144)
Alguns _Webhooks_ não estão retornando o status correto para a Vindi após o processamento.
Esse comportamento afeta a aprovação dos pedidos no Magento.
Ajustar o tratamento dos _Webhooks_, para caso não haja o correto processamento, seja realizada uma retentativa pela Vindi.
Caso o evento seja processado com sucesso, o módulo irá devolver ``status: 200`` => **OK**

Ajusta retorno de Webhooks para Vindi

---

CHANGELOG.md
app/code/community/Vindi/Subscription/Helper/Api.php
app/code/community/Vindi/Subscription/Helper/Bill.php
app/code/community/Vindi/Subscription/Helper/Order.php
app/code/community/Vindi/Subscription/Trait/PaymentProcessor.php
app/code/community/Vindi/Subscription/etc/config.xml

Issue: [#2143](https://github.com/vindi/recurrent/issues/2143)
Atualmente utilizamos os produtos do tipo '**preço fixo**' para realizar o processamento de compras no Magento.
Esse modelo influencia negativamente em alteração de produtos no plano, pois em caso de _upgrade_/_downgrade_ (como alteração de quantidade de produtos ou valores), as ações são limitadas, tendo que criar um novo produto na assinatura em questão para processar essa 'adição'. 
- Utilizar produtos do tipo '**preço fixo por quantidade**', onde o preço total dos produtos se basearam no valor base; Sendo assim, uma alteração de quantidade na assinatura, irá refletir na quantidade de itens comprados no Magento.
- Ajustar o Magento para tratar os respectivos falores (produtos/faturas)

Altera tipo de Produto utilizado na criação das cobranças

---

CHANGELOG.md
app/code/community/Vindi/Subscription/Helper/Api.php
app/code/community/Vindi/Subscription/etc/config.xml

Após a implementação do PR #100 ficou pendente a remoção da repetição por quantidade de pordutos, o que duplica os produtos na fatura Vindi.
Remover a estrutura de repetição desnecessária.

Remove estrutura de repetição por quantidade de produtos

---

app/code/community/Vindi/Subscription/Helper/Order.php

Os valores e a quantidade de produtos no pedido só estão sendo alterados se houver divergência no preço unitário dos produtos.
A alteração deve ser realizada em toda renovação. 
Mover a atualização de valores e quantidade para fora da validação de divergência:
- Se houver divergência de valores, será logada uma mensagem
- Sempre serão alterados valores e quantidade dos produtos no pedido

Ajusta alteração de valores do produto no Magento

---

CHANGELOG.md
app/code/community/Vindi/Subscription/Helper/WebhookHandler.php
app/code/community/Vindi/Subscription/etc/config.xml

O evento de testes dos Webhooks Vindi está sendo respondido com o status: 422
Como esse teste serve para validar a comunicação entre Vindi x Magento, é importante o servidor retornar o status correto.
Retornar status: 200 no processamento do evento **test**

Ajusta status do retorno para Webhook de Teste

---

app/code/community/Vindi/Subscription/Helper/Api.php
app/code/community/Vindi/Subscription/Helper/Bill.php
app/code/community/Vindi/Subscription/Helper/Order.php
app/code/community/Vindi/Subscription/Helper/Validator.php
app/code/community/Vindi/Subscription/Trait/PaymentProcessor.php

Atualmente nossos plugins por padrão cancelam uma assinatura caso o pagamento do primeiro ciclo seja rejeitado.
- O Magento está cancelando apenas compras avulsas automaticamente :heavy_check_mark: 
- Assinaturas estão sendo mantidas como **Aguardando Pagamento** :x: 
O fluxo deve ser padronizado entre os plugins :checkered_flag: 
- Caso o resultado de pagamento do pedido seja assíncrono, o Magento deve tratar corretamente os _Webhooks_ (**Charge Rejected**) recebidos
- Inserir o cancelamento automático de assinaturas caso o pagamento do primeiro ciclo seja rejeitado
- Ajustar o tratamento do evento **Charge Rejected** para se adequar ao novo comportamento

Ajusta fluxo de cancelamento de assinaturas após pagamento rejeitado

---

CHANGELOG.md
app/code/community/Vindi/Subscription/Helper/Order.php
app/code/community/Vindi/Subscription/etc/config.xml

Atualmente, Os pedidos já finalizados (Processados ou Concluídos) no Magento não são atualizados pela nossa Integração.
- Caso o pedido não tenha sido faturado
- Deve ser criada uma _invoice_ no Pedido (alterando o mesmo para **processing**) :heavy_check_mark: 
- Caso o pedido já tenha sido faturado
- O Webhook deve ser ignorado (retornando status: 200 para a Vindi) :heavy_check_mark: 
- O Webhook está sendo ignorado (retornando status: 422 para a Vindi) :x: 
- **Entrando no fluxo de retentativas de envio (por 48 horas)** :warning: 
- Inserir a validação para **pedidos já finalizados** para o _Webhook_ de **Fatura Paga**
- Retornar o status: 200 (_Evitando retentativas desnecessárias_)

Adiciona validação de pedidos finalizados para Webhook de Fatura Paga

---

CHANGELOG.md
app/code/community/Vindi/Subscription/Model/PaymentMethod.php
app/code/community/Vindi/Subscription/etc/config.xml

As informações de pagamento do pedido não estão sendo salvas, pois não foi forçado o método **save()** durante a alteração.
Inserir o **save()** no pedido após a adição das informações de pagamento.

Salva informações de pagamento no pedido

---

CHANGELOG.md
app/code/community/Vindi/Subscription/Helper/Bill.php
app/code/community/Vindi/Subscription/Helper/Order.php
app/code/community/Vindi/Subscription/Helper/Validator.php
app/code/community/Vindi/Subscription/Helper/WebhookHandler.php
app/code/community/Vindi/Subscription/etc/config.xml

Issue: [#2255](https://github.com/vindi/recurrent/issues/2255)
Durante tentativas de compra via **cartão de débito**, após o pagamento capturado com sucesso e debitado do cliente, pode haver uma nova tentativa de captura rejeitada, fazendo com que o pedido seja cancelado automaticamente no Magento.
Isso acontece pois como os Webhooks são assíncronos e o Webhook de Fatura Paga (_bill_paid_) pode chegar primeiro que os demais. Nesse caso, ele entra numa fila de espera para ser reenviado.
No entanto, as demais alterações na fatura podem ser recebidas primeiro, alterando o pedido de forma _indesejada_.
Ajustar o tratamento dos Webhooks, para que ambos sejam capazes de realizar alterações no pedido.
- Ambiente com Magento **instalado** e **configurado** [1.7 até 1.9]
- Ngrok instalado
- Acesso …

Ajusta tratativa de webhooks [Bill Paid / Bill Created]

---

CHANGELOG.md
app/code/community/Vindi/Subscription/Block/Form/Cc.php
app/code/community/Vindi/Subscription/Block/Form/Dc.php
app/code/community/Vindi/Subscription/Helper/Api.php
app/code/community/Vindi/Subscription/Helper/Order.php
app/code/community/Vindi/Subscription/Model/Observer.php
app/code/community/Vindi/Subscription/controllers/WebhookController.php
app/code/community/Vindi/Subscription/etc/config.xml

Segue meus apontamentos:
Estou atendendo um cliente que utiliza este módulo de subscription da vindi para magento 1.
O cenário é o seguinte, o cliente possui uma regra de negócio específica que precisa realizar um override na seguinte class e method:
class > app/code/community/Vindi/Subscription/Model/Observer.php
method > validateAdminHtmlOrder
Ou seja:
class Cliente_VindiSubscription_Model_Observer extends Vindi_Subscription_Model_Observer
method validateAdminHtmlOrder chama o method $this->countSubscriptions($quote) que chama $this->isSubscription($product) que possuem visibilidade private, o que gera erro, pois uma class inherited não consegue chamar método private do pai, somente se for protected.
Ou seja, 
Tenho que alterar também a visibilidade do method countSubscriptions e …

Alteração da visibilidade das variáveis e métodos de private para protected

---

CHANGELOG.md
app/code/community/Vindi/Subscription/Helper/WebhookHandler.php
app/code/community/Vindi/Subscription/etc/config.xml

A chamada para o método `validateBillCreatedWebhook` está incorreta, fazendo com que o Webhooks de **Fatura criada** sejam ignorados pelo módulo Vindi.
Apesar do problema, não foram detectados impactos maiores justamente pelo tratamento realizado nos Webhooks de **Fatura paga** que hoje realizam as 2 funções (PR #111).
Ajustar a chamada do método `validateBillCreatedWebhook`

Ajusta parâmetro para webhook bill_created

---

CHANGELOG.md
app/code/community/Vindi/Subscription/Model/CreditCard.php
app/code/community/Vindi/Subscription/etc/config.xml
tests/acceptance/vindiCheckoutWithCreditCardCest.php

Ao ativar o parcelamento e configurar o número máximo de parcelas como 1, ao tentar realizar a compra, há o retorno para informar o número de parcelas, mesmo não tendo o campo para informar as parcelas.
-Configuração do método de pagamento:
-Erro apresentado no checkout:
Tratativa para setar como "1" quando o número de parcelas não for informado no checkout.

Ajusta tratativa para número de parcelas

---

app/code/community/Vindi/Subscription/Model/CreditCard.php
tests/acceptance/vindiCheckoutWithCreditCardCest.php

O PR #119 tratava o parcelamento para cartões de crédito, na primeira compra. Esse PR trata agora o parcelamento para cartões salvos no checkout.
Tratativa para setar como "1" quando o número de parcelas não for informado no checkout com o cartão de crédito salvo.

Ajusta tratativa para número de parcelas em cartões de crédito salvos

---

.semaphore/semaphore.yml

Habilitar o projeto para usar a versão 2.0 do Semaphore CI conforme a issue https://github.com/vindi/vindi-magento/issues/135
Criar arquivo de configuração (YAML) do serviço no projeto
Abrir a intrface 2.0 do Semaphore e fazer o build.
Sem riscos
Sem impactos
Ter a entrada do projeto no Semaphore 2.0 criada

adicionando configuração para o semaphore 2.0

---

CHANGELOG.md
app/code/community/Vindi/Subscription/Helper/Api.php

by: @brunoconstantino
Agora não será mais enviado um produto com valor zerado para a Vindi caso seja efetuada uma compra de produto configurável.
Na issue https://github.com/vindi/vindi-magento/issues/133, foi reportado um problema em que estão sendo colocados produtos a mais na fatura do cliente caso o produto comprado seja um produto configurável.
Estou alterando o método de criação de faturas avulsas para `$order->getAllVisibleItems()`, que só utilizará o produto principal na criação da fatura.
- Crie um produto configurável no seu ambiente Magento
- Realize a compra de uma variação
- Ao verificar a plataforma Vindi, a fatura criada deve estar da seguinte forma:
Antes da correção, a fatura estará assim:

Corrige duplicidade de produtos configuráveis
